//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.ViewResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Firma.ViewResources.BaseResources", typeof(BaseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres główny.
        /// </summary>
        public static string AdresGlowny {
            get {
                return ResourceManager.GetString("AdresGlowny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres siedziby.
        /// </summary>
        public static string AdresSiedziby {
            get {
                return ResourceManager.GetString("AdresSiedziby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres wysyłkowy.
        /// </summary>
        public static string AdresWysylkowy {
            get {
                return ResourceManager.GetString("AdresWysylkowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresy kontrahenta.
        /// </summary>
        public static string AdresyKontrahenta {
            get {
                return ResourceManager.GetString("AdresyKontrahenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akronim.
        /// </summary>
        public static string Akronim {
            get {
                return ResourceManager.GetString("Akronim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywny użytkownik:.
        /// </summary>
        public static string AktUz {
            get {
                return ResourceManager.GetString("AktUz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywny.
        /// </summary>
        public static string Aktywny {
            get {
                return ResourceManager.GetString("Aktywny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulowane.
        /// </summary>
        public static string Anulowane {
            get {
                return ResourceManager.GetString("Anulowane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Anuluj {
            get {
                return ResourceManager.GetString("Anuluj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż produkty archiwalne.
        /// </summary>
        public static string Archiwalne {
            get {
                return ResourceManager.GetString("Archiwalne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archwiwalny.
        /// </summary>
        public static string Archwiwalny {
            get {
                return ResourceManager.GetString("Archwiwalny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zablokuj możliwość zapisu zmian.
        /// </summary>
        public static string BlokadaZapisu {
            get {
                return ResourceManager.GetString("BlokadaZapisu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane kontrahenta nie mogą być puste..
        /// </summary>
        public static string BrakDanychKontrahenta {
            get {
                return ResourceManager.GetString("BrakDanychKontrahenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brutto.
        /// </summary>
        public static string Brutto {
            get {
                return ResourceManager.GetString("Brutto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cecha.
        /// </summary>
        public static string Cecha {
            get {
                return ResourceManager.GetString("Cecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cecha transakcji.
        /// </summary>
        public static string CechaTransakcji {
            get {
                return ResourceManager.GetString("CechaTransakcji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        public static string Cena {
            get {
                return ResourceManager.GetString("Cena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena brutto.
        /// </summary>
        public static string CenaBrutto {
            get {
                return ResourceManager.GetString("CenaBrutto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena netto.
        /// </summary>
        public static string CenaNetto {
            get {
                return ResourceManager.GetString("CenaNetto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cennik EUR.
        /// </summary>
        public static string CennikEur {
            get {
                return ResourceManager.GetString("CennikEur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cennik PLN.
        /// </summary>
        public static string CennikPln {
            get {
                return ResourceManager.GetString("CennikPln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceny.
        /// </summary>
        public static string Ceny {
            get {
                return ResourceManager.GetString("Ceny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certyfikat.
        /// </summary>
        public static string Certyfikat {
            get {
                return ResourceManager.GetString("Certyfikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas.
        /// </summary>
        public static string Czas {
            get {
                return ResourceManager.GetString("Czas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas kompletacji.
        /// </summary>
        public static string CzasKompletacji {
            get {
                return ResourceManager.GetString("CzasKompletacji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas realizacji zleceń.
        /// </summary>
        public static string CzasRealizacjiTotal {
            get {
                return ResourceManager.GetString("CzasRealizacjiTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Części.
        /// </summary>
        public static string Czesci {
            get {
                return ResourceManager.GetString("Czesci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane kontrahenta.
        /// </summary>
        public static string DaneKontrahenta {
            get {
                return ResourceManager.GetString("DaneKontrahenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane nowej pozycji zlecenia zakupu.
        /// </summary>
        public static string DaneNowejPozZZ {
            get {
                return ResourceManager.GetString("DaneNowejPozZZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane podstawowe.
        /// </summary>
        public static string DanePodstawowe {
            get {
                return ResourceManager.GetString("DanePodstawowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wystawienia.
        /// </summary>
        public static string Data_wystawienia {
            get {
                return ResourceManager.GetString("Data wystawienia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data do.
        /// </summary>
        public static string DataDo {
            get {
                return ResourceManager.GetString("DataDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data od.
        /// </summary>
        public static string DataOd {
            get {
                return ResourceManager.GetString("DataOd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data realizacji.
        /// </summary>
        public static string DataRealizacji {
            get {
                return ResourceManager.GetString("DataRealizacji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wystawienia.
        /// </summary>
        public static string DataWystawienia {
            get {
                return ResourceManager.GetString("DataWystawienia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zgłoszenia.
        /// </summary>
        public static string DataZgloszenia {
            get {
                return ResourceManager.GetString("DataZgloszenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaliczna.
        /// </summary>
        public static string Detaliczna {
            get {
                return ResourceManager.GetString("Detaliczna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docelowy.
        /// </summary>
        public static string Docelowy {
            get {
                return ResourceManager.GetString("Docelowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Dodaj {
            get {
                return ResourceManager.GetString("Dodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nową jednostkę miary.
        /// </summary>
        public static string DodajJM {
            get {
                return ResourceManager.GetString("DodajJM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Kontrahenta.
        /// </summary>
        public static string DodajKontrahenta {
            get {
                return ResourceManager.GetString("DodajKontrahenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj zlecenie serwisowe.
        /// </summary>
        public static string DodajNoweZlecenieSerwisowe {
            get {
                return ResourceManager.GetString("DodajNoweZlecenieSerwisowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowy kod PCN.
        /// </summary>
        public static string DodajPCN {
            get {
                return ResourceManager.GetString("DodajPCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Produkt.
        /// </summary>
        public static string DodajProdukt {
            get {
                return ResourceManager.GetString("DodajProdukt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowy rodzaj ceny.
        /// </summary>
        public static string DodajRCeny {
            get {
                return ResourceManager.GetString("DodajRCeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodawanie nowego statusu.
        /// </summary>
        public static string DodajStatus {
            get {
                return ResourceManager.GetString("DodajStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj zlecenie kompletacji.
        /// </summary>
        public static string DodajZlecenieKompletacji {
            get {
                return ResourceManager.GetString("DodajZlecenieKompletacji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj zlecenie zakupu.
        /// </summary>
        public static string DodajZlecenieZakupu {
            get {
                return ResourceManager.GetString("DodajZlecenieZakupu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatkowa nazwa.
        /// </summary>
        public static string DodatkowaNazwa {
            get {
                return ResourceManager.GetString("DodatkowaNazwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodawanie.
        /// </summary>
        public static string Dodawanie {
            get {
                return ResourceManager.GetString("Dodawanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument.
        /// </summary>
        public static string Dokument {
            get {
                return ResourceManager.GetString("Dokument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumenty dostawcy.
        /// </summary>
        public static string DokumentyDostawcy {
            get {
                return ResourceManager.GetString("DokumentyDostawcy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domyślna.
        /// </summary>
        public static string Domyslna {
            get {
                return ResourceManager.GetString("Domyslna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostawca.
        /// </summary>
        public static string Dostawca {
            get {
                return ResourceManager.GetString("Dostawca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępne.
        /// </summary>
        public static string Dostepne {
            get {
                return ResourceManager.GetString("Dostepne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drogowy.
        /// </summary>
        public static string Drogowy {
            get {
                return ResourceManager.GetString("Drogowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drukuj.
        /// </summary>
        public static string Drukuj {
            get {
                return ResourceManager.GetString("Drukuj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN.
        /// </summary>
        public static string Ean {
            get {
                return ResourceManager.GetString("Ean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string Edycja {
            get {
                return ResourceManager.GetString("Edycja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja kontrahenta.
        /// </summary>
        public static string EdycjaKontrahenta {
            get {
                return ResourceManager.GetString("EdycjaKontrahenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja nazwy.
        /// </summary>
        public static string EdycjaNazwy {
            get {
                return ResourceManager.GetString("EdycjaNazwy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja receptury produktu.
        /// </summary>
        public static string EdycjaRecepturyProduktu {
            get {
                return ResourceManager.GetString("EdycjaRecepturyProduktu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj recepturę kompletacji produktu.
        /// </summary>
        public static string EdytujReceptureProduktu {
            get {
                return ResourceManager.GetString("EdytujReceptureProduktu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr.
        /// </summary>
        public static string Filtr {
            get {
                return ResourceManager.GetString("Filtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrowanie.
        /// </summary>
        public static string Filtrowanie {
            get {
                return ResourceManager.GetString("Filtrowanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h:m:s.
        /// </summary>
        public static string FormatCzasu {
            get {
                return ResourceManager.GetString("FormatCzasu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Główny.
        /// </summary>
        public static string Glowny {
            get {
                return ResourceManager.GetString("Glowny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gotówka.
        /// </summary>
        public static string Gotowka {
            get {
                return ResourceManager.GetString("Gotowka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gwarancyjne.
        /// </summary>
        public static string Gwarancyjne {
            get {
                return ResourceManager.GetString("Gwarancyjne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonogram pracy montażysty.
        /// </summary>
        public static string HarmonogramPracy {
            get {
                return ResourceManager.GetString("HarmonogramPracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurtowa.
        /// </summary>
        public static string Hurtowa {
            get {
                return ResourceManager.GetString("Hurtowa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Produktu.
        /// </summary>
        public static string IdProduktu {
            get {
                return ResourceManager.GetString("IdProduktu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość.
        /// </summary>
        public static string Ilosc {
            get {
                return ResourceManager.GetString("Ilosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość zleceń.
        /// </summary>
        public static string IloscZlecen {
            get {
                return ResourceManager.GetString("IloscZlecen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość zlecona.
        /// </summary>
        public static string IloscZlecona {
            get {
                return ResourceManager.GetString("IloscZlecona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość zrealizowana.
        /// </summary>
        public static string IloscZrealizowana {
            get {
                return ResourceManager.GetString("IloscZrealizowana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje.
        /// </summary>
        public static string Informacje {
            get {
                return ResourceManager.GetString("Informacje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inna zagraniczna (poza UE).
        /// </summary>
        public static string InnaZagraniczna {
            get {
                return ResourceManager.GetString("InnaZagraniczna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena nie może być ujemna..
        /// </summary>
        public static string InvalidCena {
            get {
                return ResourceManager.GetString("InvalidCena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole z danymi dostawcy nie może być puste..
        /// </summary>
        public static string InvalidDaneDostawcy {
            get {
                return ResourceManager.GetString("InvalidDaneDostawcy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data realizacji musi być datą przyszłą..
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data realizacji nie może przypadać w dni wolne od pracy..
        /// </summary>
        public static string InvalidDataDay {
            get {
                return ResourceManager.GetString("InvalidDataDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zlecenie nie zawiera żadnych pozycji..
        /// </summary>
        public static string InvalidDataGrid {
            get {
                return ResourceManager.GetString("InvalidDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oczekiwana data realizacji musi być datą przyszłą..
        /// </summary>
        public static string InvalidDataOczekiwana {
            get {
                return ResourceManager.GetString("InvalidDataOczekiwana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzona data realizacji musi być datą przyszłą..
        /// </summary>
        public static string InvalidDataPotwierdzona {
            get {
                return ResourceManager.GetString("InvalidDataPotwierdzona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość musi być liczbą większą od 0..
        /// </summary>
        public static string InvalidIlosc {
            get {
                return ResourceManager.GetString("InvalidIlosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy musi mieć format &apos;00-000&apos;..
        /// </summary>
        public static string InvalidKod {
            get {
                return ResourceManager.GetString("InvalidKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod produktu nie może być pusty..
        /// </summary>
        public static string InvalidKodNull {
            get {
                return ResourceManager.GetString("InvalidKodNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa kraju pochodzenia nie może być pusta..
        /// </summary>
        public static string InvalidKrajNull {
            get {
                return ResourceManager.GetString("InvalidKrajNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa produktu nie może być pusta..
        /// </summary>
        public static string InvalidNazwaNull {
            get {
                return ResourceManager.GetString("InvalidNazwaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer NIP musi składać się z dzisięciu cyfr..
        /// </summary>
        public static string InvalidNipDlugosc {
            get {
                return ResourceManager.GetString("InvalidNipDlugosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer NIP musi składać się wyłącznie z cyfr..
        /// </summary>
        public static string InvalidNipZnak {
            get {
                return ResourceManager.GetString("InvalidNipZnak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabat musi być z zakresu 0-100..
        /// </summary>
        public static string InvalidRabat {
            get {
                return ResourceManager.GetString("InvalidRabat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka miary.
        /// </summary>
        public static string JednostkaMiary {
            get {
                return ResourceManager.GetString("JednostkaMiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J.m..
        /// </summary>
        public static string Jm {
            get {
                return ResourceManager.GetString("Jm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalkulacja kosztów zlecenia serwisowego.
        /// </summary>
        public static string KalkKoszZlSer {
            get {
                return ResourceManager.GetString("KalkKoszZlSer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalkulacja.
        /// </summary>
        public static string Kalkulacja {
            get {
                return ResourceManager.GetString("Kalkulacja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalkulacja czasu kompletacji.
        /// </summary>
        public static string KalkulacjaCzasuKompletacji {
            get {
                return ResourceManager.GetString("KalkulacjaCzasuKompletacji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod/Nazwa/Nip.
        /// </summary>
        public static string KNN {
            get {
                return ResourceManager.GetString("KNN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        public static string Kod {
            get {
                return ResourceManager.GetString("Kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod KGO.
        /// </summary>
        public static string KodKgo {
            get {
                return ResourceManager.GetString("KodKgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod odpadu.
        /// </summary>
        public static string KodOdpadu {
            get {
                return ResourceManager.GetString("KodOdpadu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy.
        /// </summary>
        public static string KodPocztowy {
            get {
                return ResourceManager.GetString("KodPocztowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolejowy.
        /// </summary>
        public static string Kolejowy {
            get {
                return ResourceManager.GetString("Kolejowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolumny.
        /// </summary>
        public static string Kolumny {
            get {
                return ResourceManager.GetString("Kolumny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konstruktor filtra.
        /// </summary>
        public static string KonstruktorFiltra {
            get {
                return ResourceManager.GetString("KonstruktorFiltra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrahenci.
        /// </summary>
        public static string Kontrahenci {
            get {
                return ResourceManager.GetString("Kontrahenci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrahent.
        /// </summary>
        public static string Kontrahent {
            get {
                return ResourceManager.GetString("Kontrahent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrahent docelowy.
        /// </summary>
        public static string KontrahentDocelowy {
            get {
                return ResourceManager.GetString("KontrahentDocelowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koszt.
        /// </summary>
        public static string Koszt {
            get {
                return ResourceManager.GetString("Koszt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koszt ewidencyjny.
        /// </summary>
        public static string KosztEwidencyjny {
            get {
                return ResourceManager.GetString("KosztEwidencyjny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koszt kalkulacyjny.
        /// </summary>
        public static string KosztKalkulacyjny {
            get {
                return ResourceManager.GetString("KosztKalkulacyjny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj.
        /// </summary>
        public static string Kraj {
            get {
                return ResourceManager.GetString("Kraj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krajowa.
        /// </summary>
        public static string Krajowa {
            get {
                return ResourceManager.GetString("Krajowa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj pochodzenia.
        /// </summary>
        public static string KrajPochodzenia {
            get {
                return ResourceManager.GetString("KrajPochodzenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj wysyłki.
        /// </summary>
        public static string KrajWysylki {
            get {
                return ResourceManager.GetString("KrajWysylki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Księgowość.Dyrekcja.Biuro.
        /// </summary>
        public static string KsDyBi {
            get {
                return ResourceManager.GetString("KsDyBi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Księgowość.Dyrekcja.Biuro.Handlowy.
        /// </summary>
        public static string KsDyBiHa {
            get {
                return ResourceManager.GetString("KsDyBiHa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Księgowość.Dyrekcja.Biuro.Handlowy.Serwis.
        /// </summary>
        public static string KsDyBiHaSe {
            get {
                return ResourceManager.GetString("KsDyBiHaSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Księgowość.Dyrekcja.Biuro.Magazyn.Serwis.
        /// </summary>
        public static string KsDyBiMaSe {
            get {
                return ResourceManager.GetString("KsDyBiMaSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Księgowość.Dyrekcja.Biuro.Serwis.
        /// </summary>
        public static string KsDyBiSe {
            get {
                return ResourceManager.GetString("KsDyBiSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Łączny czas.
        /// </summary>
        public static string LacznyCzas {
            get {
                return ResourceManager.GetString("LacznyCzas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista dostawców.
        /// </summary>
        public static string ListaDostawcow {
            get {
                return ResourceManager.GetString("ListaDostawcow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Kontrahentów.
        /// </summary>
        public static string ListaKontrahentow {
            get {
                return ResourceManager.GetString("ListaKontrahentow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Produktów.
        /// </summary>
        public static string ListaProduktow {
            get {
                return ResourceManager.GetString("ListaProduktow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista za.
        /// </summary>
        public static string ListaZa {
            get {
                return ResourceManager.GetString("ListaZa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Zleceń.
        /// </summary>
        public static string ListaZlecen {
            get {
                return ResourceManager.GetString("ListaZlecen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista zleceń zakupu.
        /// </summary>
        public static string ListaZlecenZakupu {
            get {
                return ResourceManager.GetString("ListaZlecenZakupu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotniczy.
        /// </summary>
        public static string Lotniczy {
            get {
                return ResourceManager.GetString("Lotniczy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lp..
        /// </summary>
        public static string Lp {
            get {
                return ResourceManager.GetString("Lp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazyn.
        /// </summary>
        public static string Magazyn {
            get {
                return ResourceManager.GetString("Magazyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazyn części.
        /// </summary>
        public static string MagazynCzesci {
            get {
                return ResourceManager.GetString("MagazynCzesci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazyn docelowy.
        /// </summary>
        public static string MagazynDocelowy {
            get {
                return ResourceManager.GetString("MagazynDocelowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazyn główny.
        /// </summary>
        public static string MagazynGlowny {
            get {
                return ResourceManager.GetString("MagazynGlowny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazyn reklamacji.
        /// </summary>
        public static string MagazynReklamacji {
            get {
                return ResourceManager.GetString("MagazynReklamacji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malejąco.
        /// </summary>
        public static string Malejaco {
            get {
                return ResourceManager.GetString("Malejaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka.
        /// </summary>
        public static string Marka {
            get {
                return ResourceManager.GetString("Marka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marża.
        /// </summary>
        public static string Marza {
            get {
                return ResourceManager.GetString("Marza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto.
        /// </summary>
        public static string Miasto {
            get {
                return ResourceManager.GetString("Miasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejscowość.
        /// </summary>
        public static string Miejscowosc {
            get {
                return ResourceManager.GetString("Miejscowosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modyfikował.
        /// </summary>
        public static string Modyfikowal {
            get {
                return ResourceManager.GetString("Modyfikowal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montażysta.
        /// </summary>
        public static string Montazysta {
            get {
                return ResourceManager.GetString("Montazysta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morski.
        /// </summary>
        public static string Morski {
            get {
                return ResourceManager.GetString("Morski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string Nazwa {
            get {
                return ResourceManager.GetString("Nazwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netto.
        /// </summary>
        public static string Netto {
            get {
                return ResourceManager.GetString("Netto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepotwierdzone.
        /// </summary>
        public static string Niepotwierdzone {
            get {
                return ResourceManager.GetString("Niepotwierdzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to niezrealizowane.
        /// </summary>
        public static string Niezrealizowane {
            get {
                return ResourceManager.GetString("Niezrealizowane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nip.
        /// </summary>
        public static string Nip {
            get {
                return ResourceManager.GetString("Nip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowy sposób płatności.
        /// </summary>
        public static string NowaPlatnosc {
            get {
                return ResourceManager.GetString("NowaPlatnosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowy typ transakcji.
        /// </summary>
        public static string NowaTransakcja {
            get {
                return ResourceManager.GetString("NowaTransakcja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowego montażystę.
        /// </summary>
        public static string NowyMonter {
            get {
                return ResourceManager.GetString("NowyMonter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy rodzaj ceny:.
        /// </summary>
        public static string NowyRodzajCeny {
            get {
                return ResourceManager.GetString("NowyRodzajCeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowy rodzaj transportu.
        /// </summary>
        public static string NowyRodzTransportu {
            get {
                return ResourceManager.GetString("NowyRodzTransportu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowy sposób dostawy.
        /// </summary>
        public static string NowySpDostawy {
            get {
                return ResourceManager.GetString("NowySpDostawy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowy status .
        /// </summary>
        public static string NowyStatus {
            get {
                return ResourceManager.GetString("NowyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr domu.
        /// </summary>
        public static string NrDomu {
            get {
                return ResourceManager.GetString("NrDomu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr lokalu.
        /// </summary>
        public static string NrLokalu {
            get {
                return ResourceManager.GetString("NrLokalu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr oferty.
        /// </summary>
        public static string NrOferty {
            get {
                return ResourceManager.GetString("NrOferty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr oferty dostawcy.
        /// </summary>
        public static string NrOfertyDost {
            get {
                return ResourceManager.GetString("NrOfertyDost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr potwierdzenia.
        /// </summary>
        public static string NrPotwierdzenia {
            get {
                return ResourceManager.GetString("NrPotwierdzenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr zlecenia serwisowego.
        /// </summary>
        public static string NrZleceniaSerwisowego {
            get {
                return ResourceManager.GetString("NrZleceniaSerwisowego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerowanie automatyczne.
        /// </summary>
        public static string NumerowanieAuto {
            get {
                return ResourceManager.GetString("NumerowanieAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obłożenie dzienne wybranego montażysty.
        /// </summary>
        public static string ObłozenieDzienneMontazysty {
            get {
                return ResourceManager.GetString("ObłozenieDzienneMontazysty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsługa zlecenia.
        /// </summary>
        public static string ObslugaZlecenia {
            get {
                return ResourceManager.GetString("ObslugaZlecenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data oczekiwana.
        /// </summary>
        public static string OczekiwanaDataR {
            get {
                return ResourceManager.GetString("OczekiwanaDataR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odbiorca.
        /// </summary>
        public static string Odbiorca {
            get {
                return ResourceManager.GetString("Odbiorca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odbiór własny.
        /// </summary>
        public static string OdbiorWlasny {
            get {
                return ResourceManager.GetString("OdbiorWlasny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpłatne.
        /// </summary>
        public static string Odplatne {
            get {
                return ResourceManager.GetString("Odplatne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedzialny.
        /// </summary>
        public static string Odpowiedzialny {
            get {
                return ResourceManager.GetString("Odpowiedzialny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odśwież.
        /// </summary>
        public static string Odswiez {
            get {
                return ResourceManager.GetString("Odswiez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odwrotne obciążenie.
        /// </summary>
        public static string OdwrotneObciazenie {
            get {
                return ResourceManager.GetString("OdwrotneObciazenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis zlecenia.
        /// </summary>
        public static string OpisZlecenia {
            get {
                return ResourceManager.GetString("OpisZlecenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programie.
        /// </summary>
        public static string OProgramie {
            get {
                return ResourceManager.GetString("OProgramie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoba zgłaszająca.
        /// </summary>
        public static string OsobaZglaszajaca {
            get {
                return ResourceManager.GetString("OsobaZglaszajaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz.
        /// </summary>
        public static string Otworz {
            get {
                return ResourceManager.GetString("Otworz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz listę kontrahentów.
        /// </summary>
        public static string OtworzListeKontr {
            get {
                return ResourceManager.GetString("OtworzListeKontr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz listę produktów.
        /// </summary>
        public static string OtworzListeProduktow {
            get {
                return ResourceManager.GetString("OtworzListeProduktow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz listę zleceń kompletacji.
        /// </summary>
        public static string OtworzListeZK {
            get {
                return ResourceManager.GetString("OtworzListeZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz listę zleceń zakupu.
        /// </summary>
        public static string OtworzListeZZ {
            get {
                return ResourceManager.GetString("OtworzListeZZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametry zamówienia.
        /// </summary>
        public static string ParametryZamowienia {
            get {
                return ResourceManager.GetString("ParametryZamowienia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametry zlecenia.
        /// </summary>
        public static string ParametryZlecenia {
            get {
                return ResourceManager.GetString("ParametryZlecenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCN.
        /// </summary>
        public static string Pcn {
            get {
                return ResourceManager.GetString("Pcn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płatność.
        /// </summary>
        public static string Platnosc {
            get {
                return ResourceManager.GetString("Platnosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poczta.
        /// </summary>
        public static string Poczta {
            get {
                return ResourceManager.GetString("Poczta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podzielona płatność (MPP).
        /// </summary>
        public static string PodzielonaPlatnosc {
            get {
                return ResourceManager.GetString("PodzielonaPlatnosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż dane szczegółowe.
        /// </summary>
        public static string PokazDaneSzczegolowe {
            get {
                return ResourceManager.GetString("PokazDaneSzczegolowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż Menu Boczne.
        /// </summary>
        public static string PokazMB {
            get {
                return ResourceManager.GetString("PokazMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż Pasek Narzędzi.
        /// </summary>
        public static string PokazPN {
            get {
                return ResourceManager.GetString("PokazPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data potwierdzona.
        /// </summary>
        public static string PotwierdzonaDataR {
            get {
                return ResourceManager.GetString("PotwierdzonaDataR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzone.
        /// </summary>
        public static string Potwierdzone {
            get {
                return ResourceManager.GetString("Potwierdzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorytet.
        /// </summary>
        public static string Priorytet {
            get {
                return ResourceManager.GetString("Priorytet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorytet zlecenia.
        /// </summary>
        public static string PriorytetZlecenia {
            get {
                return ResourceManager.GetString("PriorytetZlecenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producent.
        /// </summary>
        public static string Producent {
            get {
                return ResourceManager.GetString("Producent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkcja.
        /// </summary>
        public static string Produkcja {
            get {
                return ResourceManager.GetString("Produkcja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        public static string Produkt {
            get {
                return ResourceManager.GetString("Produkt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkty.
        /// </summary>
        public static string Produkty {
            get {
                return ResourceManager.GetString("Produkty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkty uboczne.
        /// </summary>
        public static string ProduktyUboczne {
            get {
                return ResourceManager.GetString("ProduktyUboczne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przedpłata.
        /// </summary>
        public static string Przedplata {
            get {
                return ResourceManager.GetString("Przedplata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przelew.
        /// </summary>
        public static string Przelew {
            get {
                return ResourceManager.GetString("Przelew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przelicz.
        /// </summary>
        public static string Przelicz {
            get {
                return ResourceManager.GetString("Przelicz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przelicz czas kompletacji.
        /// </summary>
        public static string PrzeliczCzasKompl {
            get {
                return ResourceManager.GetString("PrzeliczCzasKompl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przyjęte.
        /// </summary>
        public static string Przyjete {
            get {
                return ResourceManager.GetString("Przyjete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabat.
        /// </summary>
        public static string Rabat {
            get {
                return ResourceManager.GetString("Rabat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabat [%].
        /// </summary>
        public static string RabatP {
            get {
                return ResourceManager.GetString("RabatP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport Montera.
        /// </summary>
        public static string RaportMontera {
            get {
                return ResourceManager.GetString("RaportMontera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporty.
        /// </summary>
        public static string Raporty {
            get {
                return ResourceManager.GetString("Raporty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport czasu realizacji ZK.
        /// </summary>
        public static string RaportZK {
            get {
                return ResourceManager.GetString("RaportZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport Zlecenia Zakupu.
        /// </summary>
        public static string RaportZZ {
            get {
                return ResourceManager.GetString("RaportZZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezerwacje.
        /// </summary>
        public static string Rezerwacje {
            get {
                return ResourceManager.GetString("Rezerwacje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj ceny.
        /// </summary>
        public static string RodzajCeny {
            get {
                return ResourceManager.GetString("RodzajCeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj transportu.
        /// </summary>
        public static string RodzajTransportu {
            get {
                return ResourceManager.GetString("RodzajTransportu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosnąco.
        /// </summary>
        public static string Rosnaco {
            get {
                return ResourceManager.GetString("Rosnaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozlicz / Zakończ zlecenie.
        /// </summary>
        public static string RozZakZlec {
            get {
                return ResourceManager.GetString("RozZakZlec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serwis.
        /// </summary>
        public static string Serwis {
            get {
                return ResourceManager.GetString("Serwis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serwisant.
        /// </summary>
        public static string Serwisant {
            get {
                return ResourceManager.GetString("Serwisant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siedziba.
        /// </summary>
        public static string Siedziba {
            get {
                return ResourceManager.GetString("Siedziba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Składniki.
        /// </summary>
        public static string Skladniki {
            get {
                return ResourceManager.GetString("Skladniki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zlecenie kompletacji musi zawierać przynajmniej jeden składnik..
        /// </summary>
        public static string SkladnikiMissing {
            get {
                return ResourceManager.GetString("SkladnikiMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortowanie.
        /// </summary>
        public static string Sortowanie {
            get {
                return ResourceManager.GetString("Sortowanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sposób dostawy.
        /// </summary>
        public static string SposobDostawy {
            get {
                return ResourceManager.GetString("SposobDostawy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdź dostępność aktualizacji.
        /// </summary>
        public static string SprDostAkt {
            get {
                return ResourceManager.GetString("SprDostAkt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprzedaż.
        /// </summary>
        public static string Sprzedaz {
            get {
                return ResourceManager.GetString("Sprzedaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalkulacja Średniego Czasu Realizacji Kompletacji.
        /// </summary>
        public static string SrKomp {
            get {
                return ResourceManager.GetString("SrKomp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia ilość dni realizacji zlecenia kompletacji wynosi:.
        /// </summary>
        public static string SrKompLabel {
            get {
                return ResourceManager.GetString("SrKompLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stan.
        /// </summary>
        public static string Stan {
            get {
                return ResourceManager.GetString("Stan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stany.
        /// </summary>
        public static string Stany {
            get {
                return ResourceManager.GetString("Stany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stany zerowe magazynu.
        /// </summary>
        public static string StanyZeroMag {
            get {
                return ResourceManager.GetString("StanyZeroMag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stany zerowe sprzedaży.
        /// </summary>
        public static string StanyZeroSprz {
            get {
                return ResourceManager.GetString("StanyZeroSprz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staus zlecenia.
        /// </summary>
        public static string StausZlecenia {
            get {
                return ResourceManager.GetString("StausZlecenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stawka akcyzy.
        /// </summary>
        public static string StawkaAkcyzy {
            get {
                return ResourceManager.GetString("StawkaAkcyzy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stawka cła.
        /// </summary>
        public static string StawkaCla {
            get {
                return ResourceManager.GetString("StawkaCla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stawka KGO.
        /// </summary>
        public static string StawkaKgo {
            get {
                return ResourceManager.GetString("StawkaKgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stawka VAT sprzedaży.
        /// </summary>
        public static string StawkaVatSprzedazy {
            get {
                return ResourceManager.GetString("StawkaVatSprzedazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stawka VAT zakupu:.
        /// </summary>
        public static string StawkaVatZakupu {
            get {
                return ResourceManager.GetString("StawkaVatZakupu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWW/PKWiU.
        /// </summary>
        public static string SWWPKWiU {
            get {
                return ResourceManager.GetString("SWWPKWiU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukana fraza.
        /// </summary>
        public static string SzukanaFraza {
            get {
                return ResourceManager.GetString("SzukanaFraza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt zaliczeniowy kursu Tworzenie Interfejsów Użytkownika.
        /// </summary>
        public static string Text1 {
            get {
                return ResourceManager.GetString("Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonał: Michał Kalinowski.
        /// </summary>
        public static string Text2 {
            get {
                return ResourceManager.GetString("Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kierunek: Studia podyplomowe.
        /// </summary>
        public static string Text3 {
            get {
                return ResourceManager.GetString("Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specjalność: Programowanie Aplikacji Biznesowych.
        /// </summary>
        public static string Text4 {
            get {
                return ResourceManager.GetString("Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Towar.
        /// </summary>
        public static string Towar {
            get {
                return ResourceManager.GetString("Towar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Towary Obce.
        /// </summary>
        public static string TowaryObce {
            get {
                return ResourceManager.GetString("TowaryObce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transakcja.
        /// </summary>
        public static string Transakcja {
            get {
                return ResourceManager.GetString("Transakcja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string Typ {
            get {
                return ResourceManager.GetString("Typ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ zlecenia.
        /// </summary>
        public static string TypZlecenia {
            get {
                return ResourceManager.GetString("TypZlecenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U kontrahenta.
        /// </summary>
        public static string UKontrahenta {
            get {
                return ResourceManager.GetString("UKontrahenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukryj Menu Boczne.
        /// </summary>
        public static string UkryjMB {
            get {
                return ResourceManager.GetString("UkryjMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukryj Pasek Narzędzi.
        /// </summary>
        public static string UkryjPN {
            get {
                return ResourceManager.GetString("UkryjPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        public static string Ulica {
            get {
                return ResourceManager.GetString("Ulica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usługa.
        /// </summary>
        public static string Usluga {
            get {
                return ResourceManager.GetString("Usluga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Usun {
            get {
                return ResourceManager.GetString("Usun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń wybrany rodzaj ceny.
        /// </summary>
        public static string UsunRCeny {
            get {
                return ResourceManager.GetString("UsunRCeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utworzył.
        /// </summary>
        public static string Utworzyl {
            get {
                return ResourceManager.GetString("Utworzyl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwagi.
        /// </summary>
        public static string Uwagi {
            get {
                return ResourceManager.GetString("Uwagi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwagi serwisu.
        /// </summary>
        public static string UwagiSerwisu {
            get {
                return ResourceManager.GetString("UwagiSerwisu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string Vat {
            get {
                return ResourceManager.GetString("Vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waluta.
        /// </summary>
        public static string Waluta {
            get {
                return ResourceManager.GetString("Waluta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość brutto.
        /// </summary>
        public static string WartoscBrutto {
            get {
                return ResourceManager.GetString("WartoscBrutto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość netto.
        /// </summary>
        public static string WartoscNetto {
            get {
                return ResourceManager.GetString("WartoscNetto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość zamówienia.
        /// </summary>
        public static string WartoscZamowienia {
            get {
                return ResourceManager.GetString("WartoscZamowienia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wewnątrzwspólnotowa.
        /// </summary>
        public static string Wewnatrzwspolnotowa {
            get {
                return ResourceManager.GetString("Wewnatrzwspolnotowa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widoczność kolumn.
        /// </summary>
        public static string WidocznoscKolumn {
            get {
                return ResourceManager.GetString("WidocznoscKolumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widok.
        /// </summary>
        public static string Widok {
            get {
                return ResourceManager.GetString("Widok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Właściciel.
        /// </summary>
        public static string Wlasciciel {
            get {
                return ResourceManager.GetString("Wlasciciel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włącz filtrowanie listy.
        /// </summary>
        public static string WlFiltrListy {
            get {
                return ResourceManager.GetString("WlFiltrListy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszyscy Kontrahenci.
        /// </summary>
        public static string WszyscyKontrahenci {
            get {
                return ResourceManager.GetString("WszyscyKontrahenci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie.
        /// </summary>
        public static string Wszystkie {
            get {
                return ResourceManager.GetString("Wszystkie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie Zlecenia.
        /// </summary>
        public static string WszystkieZlecenia {
            get {
                return ResourceManager.GetString("WszystkieZlecenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz.
        /// </summary>
        public static string Wybierz {
            get {
                return ResourceManager.GetString("Wybierz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz dostawcę.
        /// </summary>
        public static string WybierzDostawce {
            get {
                return ResourceManager.GetString("WybierzDostawce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz kolumnę.
        /// </summary>
        public static string WybierzKolumne {
            get {
                return ResourceManager.GetString("WybierzKolumne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz Kontrahenta.
        /// </summary>
        public static string WybierzKontrahenta {
            get {
                return ResourceManager.GetString("WybierzKontrahenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybór kontrahenta z bazy.
        /// </summary>
        public static string WyborKontrahenta {
            get {
                return ResourceManager.GetString("WyborKontrahenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysłane.
        /// </summary>
        public static string Wyslane {
            get {
                return ResourceManager.GetString("Wyslane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystawił.
        /// </summary>
        public static string Wystawil {
            get {
                return ResourceManager.GetString("Wystawil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetlaj ceny.
        /// </summary>
        public static string WyswietlajCeny {
            get {
                return ResourceManager.GetString("WyswietlajCeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetlaj ilości.
        /// </summary>
        public static string WyswietlajIlosci {
            get {
                return ResourceManager.GetString("WyswietlajIlosci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysyłka kurierem.
        /// </summary>
        public static string WysylkaKurierem {
            get {
                return ResourceManager.GetString("WysylkaKurierem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukaj produkt.
        /// </summary>
        public static string WyszukajProdukt {
            get {
                return ResourceManager.GetString("WyszukajProdukt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończ.
        /// </summary>
        public static string Zakoncz {
            get {
                return ResourceManager.GetString("Zakoncz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończone.
        /// </summary>
        public static string Zakonczone {
            get {
                return ResourceManager.GetString("Zakonczone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakup.
        /// </summary>
        public static string Zakup {
            get {
                return ResourceManager.GetString("Zakup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakup/Sprzedaż.
        /// </summary>
        public static string ZakupSprzedaz {
            get {
                return ResourceManager.GetString("ZakupSprzedaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zamawiane.
        /// </summary>
        public static string Zamawiane {
            get {
                return ResourceManager.GetString("Zamawiane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        public static string Zamknij {
            get {
                return ResourceManager.GetString("Zamknij", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamówienia.
        /// </summary>
        public static string Zamowienia {
            get {
                return ResourceManager.GetString("Zamowienia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamówienie potwierdzone.
        /// </summary>
        public static string ZamPotw {
            get {
                return ResourceManager.GetString("ZamPotw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Zapisz {
            get {
                return ResourceManager.GetString("Zapisz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zarezerwowane.
        /// </summary>
        public static string Zarezerwowane {
            get {
                return ResourceManager.GetString("Zarezerwowane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Zleceń Kompletacji.
        /// </summary>
        public static string ZleceniaKompletacji {
            get {
                return ResourceManager.GetString("ZleceniaKompletacji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Zleceń.
        /// </summary>
        public static string ZleceniaLista {
            get {
                return ResourceManager.GetString("ZleceniaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zlecenia Serwisowe.
        /// </summary>
        public static string ZleceniaSerwisowe {
            get {
                return ResourceManager.GetString("ZleceniaSerwisowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Łączna ilość zleceń:.
        /// </summary>
        public static string ZleceniaTotal {
            get {
                return ResourceManager.GetString("ZleceniaTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista zleceń zakupu.
        /// </summary>
        public static string ZleceniaZakLista {
            get {
                return ResourceManager.GetString("ZleceniaZakLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Zleceń Zakupu.
        /// </summary>
        public static string ZleceniaZakupu {
            get {
                return ResourceManager.GetString("ZleceniaZakupu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zlecenie Kompletacji.
        /// </summary>
        public static string ZlecKomp {
            get {
                return ResourceManager.GetString("ZlecKomp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zlecenie Serwisowe.
        /// </summary>
        public static string ZlecSerwis {
            get {
                return ResourceManager.GetString("ZlecSerwis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zlecenie Zakupu.
        /// </summary>
        public static string ZlecZakup {
            get {
                return ResourceManager.GetString("ZlecZakup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień.
        /// </summary>
        public static string Zmien {
            get {
                return ResourceManager.GetString("Zmien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmniejsz.
        /// </summary>
        public static string Zmniejsz {
            get {
                return ResourceManager.GetString("Zmniejsz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrealizowane.
        /// </summary>
        public static string Zrealizowane {
            get {
                return ResourceManager.GetString("Zrealizowane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrealizowane częściowo.
        /// </summary>
        public static string ZrealizowaneCzesciowo {
            get {
                return ResourceManager.GetString("ZrealizowaneCzesciowo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwiększ.
        /// </summary>
        public static string Zwieksz {
            get {
                return ResourceManager.GetString("Zwieksz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwiń / Rozwiń menu boczne.
        /// </summary>
        public static string ZwinRozwin {
            get {
                return ResourceManager.GetString("ZwinRozwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalkulacja Zleceń Zakupu.
        /// </summary>
        public static string ZZKontrahentTotal {
            get {
                return ResourceManager.GetString("ZZKontrahentTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Łączna wartość zleceń:.
        /// </summary>
        public static string ZZTotal {
            get {
                return ResourceManager.GetString("ZZTotal", resourceCulture);
            }
        }
    }
}
